name: PHP Composer

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    tests:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                php: [ 7.4, 8.0 ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl, gd, opcache
                    coverage: none

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Checking codestyle
                run: vendor/bin/ecs

            -   name: Run code checks
                run: composer run-script analyse

            -   name: Run example script (markdown)
                run: bin/doc-parser tests/test.md;

            -   name: Run example script (tex)
                run: bin/doc-parser tests/test.tex

            -   name: Run example script (rst)
                run: bin/doc-parser tests/test.rst
